package net.thousandparsec.netlib;

/**
 * A target in the visitor/double-dispatch pattern. The implementations of the
 * {@link Visitable} interface are supposed to call back to this class'
 * implementation and in the process reveal their concrete types. The visitor
 * subclass specific for a particular protocol version are autogenerated and
 * each method by default calls the {@link #handleUnhandled(Frame)} method,
 * which can be used to handle all frames in one place; overriden callback
 * methods which do not call superimplementation will not call this method, so
 * this method receives all {@link Frame}s not handled by the concrete
 * subclass.
 * 
 * @author ksobolewski
 */
public abstract class Visitor<V extends Visitor<V>>
{
	public void handleUnhandled(Frame<V> frame)
	{
		//NOP here
	}
}
